### ISSUE TITLE
Character inside a field value mangled 

### ISSUE THREAD

**Issue by Photon89** [dbro/csvquote#23]
I have an issue with a comma inside a field value which gets transformed into an unreadable character. It is best seen on a screenshot, the first line is from the original CSV file, the second one is after piping by csvquote:

![Auswahl_556](https://github.com/user-attachments/assets/c5733cc2-03df-418a-a7d5-129bad00b66d)

Here are the copy&pasted fields:

Original: "Lima, Peru"
After csvquote: "Lima Peru"

**Comment by dbro** [comment]
This is the expected behavior. Usually csvquote is used twice in a pipeline: the first call is to transform the embedded field separators and record separators into nonprinting characters, as your screenshot illustrates. After this first usage, the data can be operated on by other commands such as awk and cut, then after those operations are done there can be a second call with a "-u" option to restore the embedded separators.

Feel free to provide the full pipeline command to continue this discussion. Until then I will mark this as closed.

**Comment by Photon89** [comment]
Thanks for your fast reply and sorry, if I provided insufficient information!

I access the fields with

```
FIELD1=$(echo $LINE | csvquote | cut -d "," -f 7 | tr ';' ',');
FIELD2=$(echo $LINE | csvquote | cut -d "," -f 8 | tr ';' ',');
...
```

etc.  inside a loop. Then put them together into a new .csv file by echoing them with

```
NEWLINE="${FIELD1};${FIELD2};...";
echo $NEWLINE >> "${OUTPUT}";
```

But issue is present after echo `$LINE | csvquote` and stays like this in the final output.

So, as you can see, I read in a .csv file with commas as separators, cut them to access the field values and then put the field values together, now separated with semicolons.

Obviously, the aim of the script is not just to switch from commas to semicolons as separators, I also do some further changes, but the issue is already present in this minimal example.

Please let me know if I can provide further information to help solve this issue!

**Comment by dbro** [comment]
try adding the "-u" option to the second call to csvquote:

`echo $LINE | csvquote -u`

**Comment by Photon89** [comment]
Sorry, I didn't read your original comment carefully enough, it works now with

`FIELD1=$(echo $LINE | csvquote | cut -d "," -f 7 | tr ';' ',' | csvquote -u);`

Thanks for your support!
