### ISSUE TITLE
Eating up comma (,) in output

### ISSUE THREAD

**Issue by flagsoft** [dbro/csvquote#9]
Hello, would be a great tool. According to the example a comma within a quoted field should be no problem, BUT:

```
$ ./csvquote
"abc","def,g"
"abc","defg"    <-- Look here: comma is missing in "def,g" !!
$
```
What's going on here? This should work, according to the doc.
Please help.

Other example:
```
$ echo 'field1,"field2, has a comma in it","field 3 has a ""Quoted String"" in it"' | ./csvquote | cut -d, -f2
"field2 has a comma in it"  <-- Look here, comma is missing !!
```

System: OS X El Capitan 10.11.6. just used standard "csvquote.c" version, make.

**Comment by flagsoft** [comment]
This seems to work, but why are two calls to csvquote required ? note the last "csvquote -u" at the end, to ***magically*** "restore" the "missing comma":

```
echo 'field1,"field2, has a comma in it","field 3 has a ""Quoted String"" in it"' | ./csvquote | cut -d, -f2 | ./csvquote -u
"field2, has a comma in it"
```

But why is that required?

What's the hidden undocumented -s switch for? (SANITIZE_MODE)
```
case 's':
                op_mode = SANITIZE_MODE;
```

**Comment by dbro** [comment]
Hi Mike-
That's correct. Here's the relevant passage from the documentation describing what happens:

> By using csvquote, you temporarily replace the special characters inside quoted fields with harmless nonprinting characters that can be processed as data by regular text tools. At the end of processing the text, these nonprinting characters are restored to their previous values.

If you were to look at the output of the command from your first message in a hex editor, you would see that the comma (hex code 2c) has been replaced by a nonprinting character with hex code 1f :

`$ echo 'field1,"field2, has a comma in it","field 3 has a ""Quoted String"" in it"' | ./csvquote | cut -d, -f2 | hexdump`
> 0000000 6622 6569 646c 1f32 6820 7361 6120 6320
0000010 6d6f 616d 6920 206e 7469 0a22
000001c

Compare that output with the version that happens when the commas have been restored:

`$ echo 'field1,"field2, has a comma in it","field 3 has a ""Quoted String"" in it"' | ./csvquote | cut -d, -f2 | ./csvquote -u | hexdump`
> 0000000 6622 6569 646c 2c32 6820 7361 6120 6320
0000010 6d6f 616d 6920 206e 7469 0a22
000001c

**Comment by dbro** [comment]
re the -s parameter to specify "sanitize mode" : it's the default mode, so does not need to be documented or used in practice.
